### PR TITLE
[VCDA-2366] Tkgm ubuntu 20 antrea template

### PR DESCRIPTION
**Pull request by ltimothy7**
I have tested created a cluster with 1 control plane node and 1 worker and have run a simple hello world app on it.

---
This change is [Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1)

### CODE REVIEW

**Review by rocknes — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

___
*[template.yaml, line 7 at r1](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gVe3s6IvRIYcWtH0-:-M_gVe3t4tAOnmJvc7aY:b53o328) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/9e39ea264b6902523ebd99049f91e4a60fb511a4/template.yaml#L7)):*
> ```YAML
>     description: "Ubuntu 20.04, Docker-ce 19.03.15, Kubernetes 1.20.4, Antrea 0.11.3"
>     mem: 2048
>     name: ubuntu-20.04_k8-1.20_antrea-0.11
> ```

nit: the name of template should be changed to .._tkgm-1.20_.. later on
___
*[template.yaml, line 38 at r1](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gW-N12CQQV0zajm_p:-M_gW-N12CQQV0zajm_q:bbo5tgw) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/9e39ea264b6902523ebd99049f91e4a60fb511a4/template.yaml#L38)):*
> ```YAML
>     cni_version: "2.6.5"
>     upgrade_from:
>       - "ubuntu-16.04_k8-1.19_weave-2.6.5"
> ```

Keep this empty, this template won't be upgradable from any other template.
___
*[scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/cust.sh, line 42 at r1](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gWXyy4ifNyiDx8k46:-M_gWXyzEc5X6aZ84aDP:b3qajk6) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/9e39ea264b6902523ebd99049f91e4a60fb511a4/scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/cust.sh#L42)):*
> ```Shell
> curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
> # 'http://apt.kubernetes.io kubernetes-focal Release' does not have a Release file, so using xenial
> echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" >> /etc/apt/sources.list.d/kubernetes.list
> ```

xenial is ubuntu 16 right? we should target something that is more suitable for ubuntu 20.
___
*[scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/mstr.sh, line 8 at r2](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gZ6vVEgdwgpGAyyZu:-M_gZ6vW53DXFS5Ngmyz:b-juy8ln) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/d225c43773b7b9eaa5f4ac7d560043c8d74595ea/scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/mstr.sh#L8)):*
> ```Shell
>   --service-cidr=100.77.0.0/16 \
>   --kubernetes-version=1.20.4+vmware.1-1 \
>   --image-repository=projects.registry.vmware.com/tkg \
> ```

I doubt if this image repository option is required or not .. additionally harbor registry needs credentials iirc.

**Review by rocknes — COMMENTED** [review]
Take a look at https://github.com/andrew-ni/container-service-extension-templates/tree/tkg-cp/scripts/ubuntu-16.04_tkg-1.17_weave-2.5.2_rev1
to see how the current TKG plus template works.

> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-:-M_gZQga9RT_gtkGqTLW:bekju2k)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @rocknes)

___
*[template.yaml, line 38 at r1](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gW-N12CQQV0zajm_p:-M_ghE-v7aWbJORKYfb7:by5lq4m) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/9e39ea264b6902523ebd99049f91e4a60fb511a4/template.yaml#L38)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Keep this empty, this template won't be upgradable from any other template.
</blockquote></details>

This is for the ubuntu 16 k8s 1.20 template. Did you mean for a different template? The tkgm template does not currently have anything listed for upgrade_from, but I will make it empty
___
*[scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/cust.sh, line 42 at r1](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gWXyy4ifNyiDx8k46:-M_gp1gk7BBxLFzUZTxr:bq84vhs) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/9e39ea264b6902523ebd99049f91e4a60fb511a4/scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/cust.sh#L42)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

xenial is ubuntu 16 right? we should target something that is more suitable for ubuntu 20.
</blockquote></details>

Thanks Aritra. I checked, and bionic (ubuntu 18) still has the problem. Using this xenial version is also listed on the this kubernetes documentation
___
*[scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/mstr.sh, line 8 at r2](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gZ6vVEgdwgpGAyyZu:-M_h3vak-_sM5CrOBP5b:bt5g2gy) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/d225c43773b7b9eaa5f4ac7d560043c8d74595ea/scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/mstr.sh#L8)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I doubt if this image repository option is required or not .. additionally harbor registry needs credentials iirc.
</blockquote></details>

I will check this out once I create another cluster, thanks

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/cust.sh, line 59 at r4](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-Ma-_j6_ARildbnp2nXZ:-Ma-_j6_ARildbnp2nX_:b-jzoq6) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/219d23150536f3ebd1e88e107e09dc69d0b15232/scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/cust.sh#L59)):*
> ```Shell
> 
> # Install kubernetes components, coredns, and antrea binary
> wget http://build-squid.eng.vmware.com/build/mts/release/bora-17654488/publish/lin64/kubernetes/images/kube-proxy-v1.20.4_vmware.1.tar.gz
> ```

Is build-squid accessible out of VMware network?

**Comment by ltimothy7** [comment]
___
*[scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/cust.sh, line 59 at r4](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-Ma-_j6_ARildbnp2nXZ:-Ma-gXw63Z0VPJbsJLLr:b-v5cvi7) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/219d23150536f3ebd1e88e107e09dc69d0b15232/scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/cust.sh#L59)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is build-squid accessible out of VMware network?
</blockquote></details>

Arun and Aritra have said that this current temporary solution is fine until we have a more permanent plan

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/mstr.sh, line 8 at r2](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gZ6vVEgdwgpGAyyZu:-Ma-zIgj1x1wS8VFKn13:b-b34ri1) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/d225c43773b7b9eaa5f4ac7d560043c8d74595ea/scripts/ubuntu-20.04_k8-1.20_antrea-0.11_rev1/mstr.sh#L8)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I will check this out once I create another cluster, thanks
</blockquote></details>

I think we will need this because the default it: --image-repository "k8s.gcr.io"

**Review by rocknes — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 6 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-:-Ma0_7Mj0_tsN2uLKHU6:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[template.yaml, line 38 at r1](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gW-N12CQQV0zajm_p:-Ma0ZJle8qoOshkrsvhD:b-obsity) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/9e39ea264b6902523ebd99049f91e4a60fb511a4/template.yaml#L38)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

This is for the ubuntu 16 k8s 1.20 template. Did you mean for a different template? The tkgm template does not currently have anything listed for upgrade_from, but I will make it empty
</blockquote></details>

Sorry .. didn't realize there were more than one template definition.. there is no need to have any other template in this yaml file, just retain the tkgm one and remove everything else.
___
*[scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/cust.sh, line 46 at r5](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-Ma0ZqTsBQZqrq7CEVpY:-Ma0ZqTtAqjyaiIr_VId:b-wl21l5) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/d422b41d9c839f8e41b109e6d051ec72d7a42c1c/scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/cust.sh#L46)):*
> ```Shell
> add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
> apt-get -q update -o Acquire::Retries=3 -o Acquire::http::No-Cache=True -o Acquire::http::Timeout=30 -o Acquire::https::No-Cache=True -o Acquire::https::Timeout=30 -o Acquire::ftp::Timeout=30
> apt-get -q install -y kubernetes-cni=0.8.7-00
> ```

Do we still need kubernetes-cni with antrea?

**Comment by ltimothy7** [comment]
___
*[scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/cust.sh, line 46 at r5](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-Ma0ZqTsBQZqrq7CEVpY:-Ma0dP8Y3XHTTOKoWUVF:b-6gb1a1) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/d422b41d9c839f8e41b109e6d051ec72d7a42c1c/scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/cust.sh#L46)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Do we still need kubernetes-cni with antrea?
</blockquote></details>

Yes, there is an error if kubernetes-cni is not preseent when installing kubelet.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1)* status: 3 of 153 files reviewed, 3 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[template.yaml, line 38 at r1](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-M_gW-N12CQQV0zajm_p:-Ma1ZT-_1Jw9SNYHpjt1:b-896fix) ([raw file](https://github.com/ltimothy7/container-service-extension-templates/blob/9e39ea264b6902523ebd99049f91e4a60fb511a4/template.yaml#L38)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Sorry .. didn't realize there were more than one template definition.. there is no need to have any other template in this yaml file, just retain the tkgm one and remove everything else.
</blockquote></details>

Done.

**Review by rocknes — COMMENTED** [review]
> Reviewed 3 of 150 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1)* status: 6 of 153 files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, 150 of 150 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ltimothy7/container-service-extension-templates/1#-:-Ma4PC1S3D8BVNW0Xkxi:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Pull request merged**
